### ISSUE TITLE
ender extender[FR] 

### ISSUE THREAD

**Issue by Razzorback05** [classicrocker883/MRiscoCProUI#102]
### Is your feature request related to a problem? Please describe.

Need to modify firmware to a z height of 400mm

### Are you looking for hardware support?

aquila g32 board , need it to print full ectension of the extender i installed

### Describe the feature you want

just need modified firmware so printer will raise to 400mm

**Comment by classicrocker883** [comment]
Yes, this is something you can do within the LCD menu itself. Navigate to **Control** > **Physical settings**

**Comment by classicrocker883** [comment]
if you can't get it to work how you want let me know
