### ISSUE TITLE
 incorrect operation

### ISSUE THREAD

**Issue by 314ru** [classicrocker883/MRiscoCProUI#11]
Аfter the start of printing, before the start of the execution of the G-code
- if you cancel the operation, the printer moves the head to an inaccessible area: the motors skip steps with a loud sound

**Comment by classicrocker883** [comment]
I think what may be happening is the order of homing in your start gcode. basically if u stop the print before it has a chance to determine its location, it may over shoot and cause this. 

I'll look into and see. 

but for now in the `advanced settings`, look for home offsets / Park Head.

change the value that, it changes the position where the head parks after a stopped or aborted print.
