### ISSUE TITLE
Extruder usually stops responding

### ISSUE THREAD

**Issue by Arson31** [classicrocker883/MRiscoCProUI#13]
Original Voxelab Aquila G32 board. The extruder would only respond to loading/unloading filament. The extruder doesn't react when clicking retract/extrude on command in Octoprint. The extruder occasionally responds and prints no problem. On one print disabling arc welder would allow the extruder to respond without having to touch other settings. I decided to flash back to Alex's firmware and the extruder responded.

**Comment by classicrocker883** [comment]
there was a recent update and it may have fixed this issue. I'll post back as soon as I compile the firmware .bin files with the updated version.
