### ISSUE TITLE
[BUG] Warning with NOZZLE_PARK_FEATURE disabled

### ISSUE THREAD

**Issue by wlkmanist** [classicrocker883/MRiscoCProUI#130]
### Did you test the latest release build?

No, but I will try it!

### Bug Description

May be it is precompiled binary issue. I don't know.

How to reproduce:
  Disable in config:
    `NOZZLE_PARK_FEATURE`
    `FILAMENT_RUNOUT_SENSOR`
    `ADVANCED_PAUSE_FEATURE`

Then I have this warning:
`.pio/build/GD32F103RC_voxelab_maple/src/src/lcd/e3v2/proui/toolbar.cpp.o:(.rodata.TBItemA+0xa4): warning: undefined reference to 'ParkHead()'`

I am not actually flashed that build (with warning) into my board. Would be cool if there is any solution to fix that because disabling that features in config can save a lot of memory.

### Printer Model

Voxelab Aquila

### Your Mainboard

Aquila GD32

### ProUI?

ProUI

### Bed Leveling

MM - Manual Mesh Bed Leveling

### Did you include your own configuration files?

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by classicrocker883** [comment]
in **Marlin\src\lcd\e3v2\proui\toolbar_def.h**

replace the line with `ParkHead` with this, and remove the ` , ` after `WriteEeprom)`:
```y
TB_ITEM(ICON_WriteEEPROM, MSG_STORE_EEPROM, WriteEeprom)
OPTARG(NOZZLE_PARK_FEATURE, TB_ITEM(ICON_Park, MSG_FILAMENT_PARK_ENABLED, ParkHead))
```

**Comment by classicrocker883** [comment]
fixed in a commit a while back
