### ISSUE TITLE
[BUG] Not working [-PLR] | No funciona

### ISSUE THREAD

**Issue by Manric0421** [classicrocker883/MRiscoCProUI#136]
### Did you test the latest release build?

Yes, and the problem still exists.

### Bug Description

[-PLR]
| Recuperación de pérdida de energía | (reanuda donde se quedó un trabajo de impresión cuando hay un corte de energía )
al momento de corte de energía y reiniciar la impresora no sale nada no da opción de iniciar trabajo no funciona

<br>
Not working [-PLR] | Power Loss Recovery | (picks up where a print job left off when there is a power outage
### Printer Model

Voxelab Aquila

### Model Type

S3

### Your Mainboard

Aquila N32

### ProUI?

ProUI

### Bed Leveling

UBL - Unified Bed Leveling

### Did you include your own configuration files?

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by classicrocker883** [comment]
can you explain how this does not work?

¿Puedes explicar cómo esto no funciona?

**Comment by Manric0421** [comment]
al momento de imprimir y si se apaga la impresora al encenderla nuevamente sale aviso de iniciar el trabajo donde estaba en aquila x3 no lo hace no recupera la impresion prende e inicia como sin recuperar donde iva el trabajo

**Comment by classicrocker883** [comment]
OK, I will look into it. did the previous April release work?
¿Funcionó la versión anterior de abril?
https://github.com/classicrocker883/MRiscoCProUI/releases/tag/2.1.3f-4

**Comment by Manric0421** [comment]
realice pruebas en Aquila s3 y Aquila x3 al reinstalar en firmware funciono de manera correcta la función [-PLR]
| Recuperación de pérdida de energía | (reanuda donde se quedó un trabajo de impresión cuando hay un corte de energía) gracias

**Comment by Manric0421** [comment]
realice pruebas en Aquila s3 y Aquila x3 al reinstalar en firmware funciono de manera correcta la función [-PLR]
| Recuperación de pérdida de energía | (reanuda donde se quedó un trabajo de impresión cuando hay un corte de energía) gracias
