### ISSUE TITLE
[BUG] Ultra-fast movements during G28 homing

### ISSUE THREAD

**Issue by Big-Channie** [classicrocker883/MRiscoCProUI#152]
### Did you test the latest release build?

Yes, and the problem still exists.

### Bug Description

During G28, printer will home X and Y to 0,0 at normal speeds, then it rockets very fast over to center and homes Z. Same issue as here I believe;

https://github.com/MarlinFirmware/Marlin/issues/27354

I'm using the August Rev.1 release;

Aquila_N32_UBL-ProUI-EX-PLR-08-14.bin

Thanks so much for making a great firmware, my Aquila X3 is my first printer and I've been using the MRiscoC fork for close to a year now. 

### Printer Model

Voxelab Aquila

### Model Type

X3

### Your Mainboard

Aquila N32

### Add-ons that could be involved

BLtouch

### ProUI-EX | Extra Features?

Yes

### Bed Leveling

UBL - Unified Bed Leveling

### Did you include your own configuration files?

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by classicrocker883** [comment]
so a recent commit from Marlin has fixed the issue. ill be posting a new release soon
