### ISSUE TITLE
Basic documentation gotcha?

### ISSUE THREAD

**Issue by Egosumumbravir** [classicrocker883/MRiscoCProUI#17]
Perhaps it's just me (and it IS probably just me) but late last night I was staring blurry eyed at the releases and trying to work out what to download.

Big point of confusion was the difference between the *.bin files and *-IS.bin files.  So I searched for "-is" and got nothing but the files themselves.  Only this morning with clear eyes and head did I finally note the comment "Input Shaping (enabled in file ending IS)*"

Searching for "is" turns up 57 matches.  Would it be beneficial to simply change the notes from "IS" to "-IS" so it's discoverable with an easy text search?

**Comment by classicrocker883** [comment]
oh sure. yes I can do that. anything else I can do let me know
