### ISSUE TITLE
[BUG] the hotend  dose not heat up  

### ISSUE THREAD

**Issue by dewey2008** [classicrocker883/MRiscoCProUI#170]
### Did you test the latest release build?

Yes, and the problem still exists.

### Bug Description

When using your build it dose not stay at 200 C but with the stock build from voxelab it stays at 200 just fine when printing 

### Printer Model

Voxelab Aquila

### Model Type

x3 plus

### Your Mainboard

Aquila N32

### Other Mainboard Type

n/a

### ProUI-EX | Extra Features?

Yes

### Bed Leveling

UBL - Unified Bed Leveling

### Did you include your own configuration files?

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by Mik-S-UMS** [comment]
Have you done a PID tune yet?

**Comment by dewey2008** [comment]
this fixed it also how do i edit the bed size to 300mm  it currently only auto leveling a 235mm x 235mm area
