### ISSUE TITLE
Missing MPC menu

### ISSUE THREAD

**Issue by kagebarton** [classicrocker883/MRiscoCProUI#25]
I enabled MPC for the hotend and while the hotend PID option was gone, there is no MPC menu. I did verify that the MPC g-codes work through the terminal.

**Comment by classicrocker883** [comment]
I believe the mpc menu has to be enabled in the dwin.cpp file which is the main file for how the UI looks. I'll look into this and see what should change.

**Comment by classicrocker883** [comment]
in the dwin.cpp file you can add

>#if ENABLED(MPCTEMP)
      MENU_ITEM_F(ICON_MPCNozzle, STR_MPC_AUTOTUNE " Settings", onDrawSubMenu, Draw_HotendMPC_Menu);
    #endif

to `void Draw_Temperature_Menu() ` and change the value 5 to 6 where it says Set_menu, before preheat_count.

not sure why the hotend PID option would be gone. make sure that (PIDTEMP) is enabled / defined.

**Comment by kagebarton** [comment]
Perfect. Thanks!

I disabled PID when I enabled MPC on the hotend.
