### ISSUE TITLE
Advanced Pause

### ISSUE THREAD

**Issue by schuh8** [classicrocker883/MRiscoCProUI#4]
Aquila w/ 4.2.7 and Creality-427-ProUI-UBL.bin . As mentioned on the reddit forum and documenting here. When starting a print and just after the start script executes I get a "advanced pause, purge or continue". The only way around the problem is to go into filament settings and deselect "enable runout". I can then restart the print and it will print normally. Sometimes when the printer is turned off the box defaults to checked and the problem reappears. Sometimes on restarting it remains unchecked.

**Comment by classicrocker883** [comment]
some boards have their runout sensor enable pin pulled `HIGH` or `LOW`. if the filament runout sensor is not plugged in this can trigger the advanced pause during print. either switch it to low or disable the feature altogether.

I mistakenly left it enabled at HIGH during compilation for this board.
