### ISSUE TITLE
H32 BUILD NoProUI

### ISSUE THREAD

**Issue by DarkSasuke** [classicrocker883/MRiscoCProUI#47]
Hello, i love what you do, will it possible to have h32 build with NoProUI for AquilaC2 ? Thanks a lot.

**Comment by classicrocker883** [comment]
The C2 with the Blue monochrome lcd right? I'm not sure if this is compatible yet with those lcds, but I'll see what I can do for u

**Comment by DarkSasuke** [comment]
yes this lcd, thanks you
