### ISSUE TITLE
Aquila X2 N32 screen jumbled and unuseable

### ISSUE THREAD

**Issue by Vanilla009** [classicrocker883/MRiscoCProUI#60]
### Did you test the latest release build?

Yes, and the problem still exists.

### Bug Description

After flashing Aquila_N32_Default-NP-ProUI-IS.bin to the Aquila X2 with an N32 board, the screen is jumbled up, making it entirely unusable.

### Printer Model

Voxelab Aquila

### Model Type

X2

### Your Mainboard

Aquila N32

### ProUI?

ProUI

### Bed Leveling

Default - No Probe / No Bed Leveling

### Did you include your own configuration files?

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

An image of what my screen looks like.
![IMG_0579 (1)](https://github.com/classicrocker883/MriscocProUI/assets/136503052/de8eebe8-c0b0-4d05-9e88-c3f1128842c8)
![IMG_0581](https://github.com/classicrocker883/MriscocProUI/assets/136503052/8f1980cb-ea2d-439b-9b4d-82c74e9b44b6)
![IMG_0580](https://github.com/classicrocker883/MriscocProUI/assets/136503052/4dcf3b5b-8353-41fd-bd8a-a781abe0ba86)
![IMG_0582](https://github.com/classicrocker883/MriscocProUI/assets/136503052/ecfb5389-c3ad-41f8-85de-77ad130de747)
![IMG_0583](https://github.com/classicrocker883/MriscocProUI/assets/136503052/d210d236-59d6-40ab-96a3-ec87a6c214db)
![IMG_0585](https://github.com/classicrocker883/MriscocProUI/assets/136503052/06406e23-31a8-44fb-9c7c-6460d4e29d91)
![IMG_0584](https://github.com/classicrocker883/MriscocProUI/assets/136503052/1acd6808-9dde-489f-b078-eb8e147d0402)
The output from M111 S247 simply gave me endless echo:M105 messages.

**Comment by classicrocker883** [comment]
you will need to flash the firmware on your LCD  
[this will show you how](https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display)  
or you can check [this readme as well](https://github.com/classicrocker883/MriscocProUI/tree/2023-July/display%20assets/Aquila%20Display%20firmware)

Download the ZIP to the repo and navigate to [here within the folders](https://github.com/classicrocker883/MriscocProUI/tree/2023-July/display%20assets/Aquila%20Display%20firmware/Firmware%20Sets)

choose one of the DWIN_SETS, I would stick with Original or Voxelab Red

[here is a Direct Download](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/classicrocker883/MriscocProUI/tree/2023-July/display%20assets/Aquila%20Display%20firmware/Firmware%20Sets) link I created so you do not have to download the whole repo if you dont want to.

**Comment by Vanilla009** [comment]
Thanks for the quick response! Your solution worked perfectly. What size should the thumbnails be? They aren't working for me.

**Comment by classicrocker883** [comment]
> Thanks for the quick response! Your solution worked perfectly. What size should the thumbnails be? They aren't working for me.

thumbnails for the G-code model preview when you select to print?  
https://github.com/classicrocker883/MriscocProUI/wiki/How-to-generate-a-gcode-preview
they should be 200x200, ~~I should make a note suggesting that,~~ but I was able to test using 230x180 and it worked fine, stretched, but fine.

what are you using for slicer? you followed the directions of putting the script in the correct folder?
another thing you need is Python installed. and it says you need to use `pip` to install Pillow

**Comment by Vanilla009** [comment]
I'm using Prusaslicer, Python installed, with pillow, 200x200 size, png. Prusaslicer throws an error - I have tried reinstalling Python and updating Pillow. I'm using Python 3.11.4. 
<img width="599" alt="image" src="https://github.com/classicrocker883/MRiscoCProUI/assets/136503052/2a8dca9f-63bd-414e-8784-fd69c947a84b">
Here is the error message Prusaslicer gives me.

**Comment by classicrocker883** [comment]
that address doesnt show up for me. I have python3.11.4 installed here  
(open up CMD - command prompt, and type the following)
```
C:\Users\Andrew>where python
C:\Program Files\Python311\python.exe
C:\Program Files\msys64\mingw64\bin\python.exe
C:\Users\Andrew\AppData\Local\Microsoft\WindowsApps\python.exe
```
for whatever reason I seem to have two different ones installed
```
C:\Users\Andrew>python --version
Python 3.11.4

C:\Users\Andrew>python3 --version
Python 3.10.12
```
```
C:\Users\Andrew>where python3
C:\Program Files\msys64\mingw64\bin\python3.exe
C:\Users\Andrew\AppData\Local\Microsoft\WindowsApps\python3.exe
```

`python` and `python3` are different (for just me at least)

you should add one of these paths to the *PATHS* environment variables. there is some documentation written up on it if you dont know how to do that.

**Comment by classicrocker883** [comment]
![showprusaslicergcode](https://github.com/classicrocker883/MRiscoCProUI/assets/18502096/f96d24ed-b1ab-4cf8-826f-d74c17b3a91f)


your slicer should look like this,

first image is in `Printer Settings` tab - General  
then `Print Settings` tab - Output Options

---
in the Post-Processing Script box, the first python exe should be the one that has Pillow installed

as you can see there is a major difference between python and python3 (for me)

```
C:\Users\Andrew>pip show pillow
Name: Pillow
Version: 10.0.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Jeffrey A. Clark (Alex)
Author-email: aclark@aclark.net
License: HPND
Location: C:\Users\Andrew\AppData\Roaming\Python\Python311\site-packages
Requires:
Required-by:

C:\Users\Andrew>python3 -m pip show pillow
Name: Pillow
Version: 10.0.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Jeffrey A. Clark (Alex)
Author-email: aclark@aclark.net
License: HPND
Location: c:\program files\msys64\mingw64\lib\python3.10\site-packages
Requires:
Required-by:
```
