### ISSUE TITLE
[LICENSE] Your Wiki is almost a copy of the Professional Firmware Wiki 

### ISSUE THREAD

**Issue by mriscoc** [classicrocker883/MRiscoCProUI#71]
### LICENSE NOTICE

All the pages and images in the Wiki at https://github.com/mriscoc/Ender3V2S1/wiki are licensed under [Creative Commons CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) License, so you need to include an author attribution and link to the original work in all the wiki pages that you copied from there.

You can find more info about this license here: https://creativecommons.org/licenses/by-nc-sa/4.0/

![](https://licensebuttons.net/l/by-nd/3.0/88x31.png)

**Comment by classicrocker883** [comment]
im working on editing the wiki, i simply copied the repo as more of a reference - with intent to change and link to the original. so that will be done in time.
