### ISSUE TITLE
How to build for N32?

### ISSUE THREAD

**Issue by KimmoHop** [classicrocker883/MRiscoCProUI#8]
When building for Aquila N32, which environment and board should be selected in platformio.io?
N32F103RE_voxelab_maple gives
`Error: Build environment 'N32F103RE_voxelab_maple' is incompatible with BOARD_CREALITY_V427. Use one of these: STM32F103RE_creality, STM32F103RE_creality_xfer, STM32F103RC_creality, STM32F103RC_creality_xfer, STM32F103RE_creality_maple`

Using BOARD_VOXELAB_AQUILA gives
`Error: Build environment 'N32F103RE_voxelab_maple' is incompatible with BOARD_VOXELAB_AQUILA. Use one of these: GD32F103RE_aquila, GD32F103RC_aquila, GD32F103RE_aquila_maple, GD32F103RC_aquila_maple, GD32F103RE_voxelab, GD32F103RC_voxelab, GD32F103RE_voxelab_maple, GD32F103RC_voxelab_maple`

What is the difference between Mriscoc-fall and MriscocProUI?

This is very confusing, when there is not enough description...

**Comment by classicrocker883** [comment]
Mriscoc-fall is the one most updated. I wrote that in the readme in the other branch. MriscocProUI was what i was working on before the latest fall update by mriscoc. So i branched off that and worked mainly on that. I will probably delete the proui branch and when there is another update merge the current Fall one with that so theres no confusion.

right now the Fall branch works when having `N32F103RE_voxelab_maple` for the default_env in platformio.ini with `MB BOARD_VOXELAB_AQUILA `

if that doesnt work what you can also do is add `-DVOXELAB_N32` to `env: GD32F103RE_voxelab_maple` or `STM32F103RE_creality_maple` (or with _RC_) build_flags after `-DTEMP_TIMER_CHAN=4`  in file --> **ini/stm32f1-maple.ini**
and use BOARD_CREALITY_V4 if you use _creality_maple_

you may have to change the **Configuration.h** file to 
>configurations/Aquila/ MM or UBL /Configuration.h

also if you are using a BLTouch, you may have to uncomment `BLTOUCH_DELAY 500` + `BLTOUCH_FORCE_SW_MODE` in **Configuration_adv.h**

im unsure if the ProUIex extra features work with the N32, but you can test it out if you want and let me know if it does. uncomment `#define ProUIex 1`
if that doesnt flash, then just comment it back.

**Comment by KimmoHop** [comment]
Marlin way of defining compatible environments is, well, awkward ;D

Thanks a lot, now MM build without ProUIex goes through (after commenting out line with onDrawUBLSlot()). I might even try it ;)

**Comment by KimmoHop** [comment]
@classicrocker883 ProUIex (at least toolbar, not sure what else there should be) seems to work fine with N32 👍
