### ISSUE TITLE
[FR] power loss function 

### ISSUE THREAD

**Issue by Kristina321** [classicrocker883/MRiscoCProUI#96]
### Is your feature request related to a problem? Please describe.

Hi you do greatest firmware, thanks a lot!!! but you delete powerloss function, in my country  power is off every day and i cant normal work with my aquila, can you help? i have N32 blt 

### Describe the feature you want

power loss function very need

**Comment by classicrocker883** [comment]
sure thats no problem. there *is* powerloss function available in the -MM (Manual Mesh), or -NoPro versions.

but you are using UBL? if so i would just need to remove some of the features. if you can tell me which ones you dont need, like the Hotend/Bed Temp Graph, homeoffsets, anything else.

**Comment by classicrocker883** [comment]
[N32_UBL_ProUI_PwrLss.zip](https://github.com/classicrocker883/MRiscoCProUI/files/13807753/N32_UBL_ProUI_PwrLss.zip)

hello I uploaded the firmware with PowerLoss enabled. this is ProUI UBL for N32, let me know if this is what you need.

I had to disable some things to make it fit:
`HAS_ESDIAG`          // View End-stop switch continuity  
`HAS_CUSTOM_COLORS`   // Able to change display colors

I will suggest you look for a UPS, (uninterruptable power supply). this will help keep power even when it is out.

or what I do is use a spare battery. like an automotive/motorcycle battery, or jumpstart powerpack. then find a 12v to 24v power converter, and plug this in where the other powersupply would go underneath. or you can find either a 24v or two 12v batteries in series and hook that up, and when power comes back you can use the meanwell powersupply under the aquila to charge the battery.

**Comment by Kristina321** [comment]
Thanks a lot for you help and happy new year for you and you family =))) battery insert is very hard for me, a think i cant do that.
 i have voxelab aquila s2 with cr touch (analog of blt) and print head- sprite pro from creality. can you do this fore my printer? sorry for my bad english. happy holliday =))

**Comment by Kristina321** [comment]
i dont use graph of temp and colors redactor

**Comment by classicrocker883** [comment]
yes I uploaded the firmware file you can download from the previous comment
it is the N32_UBL .zip file.

or I [uploaded one here ](https://github.com/classicrocker883/MRiscoCProUI/releases/tag/2.1.3f-1a)

but I will let you know that I am currently working on some fixes, you can use this for now and print, but soon come back for the updated version. I'll post a comment to let you know.

edit: oh hang on. i just read you have a Creality Sprite extruder. this may need a different thermistor type in settings. let me quickly make one with that specific change.

**Comment by Kristina321** [comment]
Ok, thanks, i will wait=))

**Comment by classicrocker883** [comment]
I am having an issue with github actions compiling and uploading the versions. ive exceeded my rate limit testing. hopefully sometime today there will be a new release! 🥇

**Comment by Kristina321** [comment]
Oh, it`s great!=)

**Comment by Kristina321** [comment]
> I am having an issue with github actions compiling and uploading the versions. ive exceeded my rate limit testing. hopefully sometime today there will be a new release! 🥇

Hi again =) Sorry, i cant found version for my aquila s2 N32 with sprite, how name it have?

**Comment by classicrocker883** [comment]
> > I am having an issue with github actions compiling and uploading the versions. ive exceeded my rate limit testing. hopefully sometime today there will be a new release! 🥇
> 
> Hi again =) Sorry, i cant found version for my aquila s2 N32 with sprite, how name it have?

Hello, there is an issue building for the release.

https://github.com/classicrocker883/MRiscoCProUI/actions/runs/7523650900/job/20477329532

as you can see `Error: API rate limit exceeded for installation ID 23315627.`

this means when you try using github Actions too much it stops any further actions, to prevent overload on the system. I'm only allow a certain number per hour.... hopefully within an hour it should be ready!

**Comment by Kristina321** [comment]
Oh, good =))) I thought you forgot of me, when i see new releese and dont find firmware =)))

**Comment by classicrocker883** [comment]
> Oh, good =))) I thought you forgot of me, when i see new releese and dont find firmware =)))

https://github.com/classicrocker883/MRiscoCProUI/releases/tag/2.1.3f-1
it should be all ready. if you dont see it within a few minutes of me posting, just wait a couple it will be there

**Comment by Kristina321** [comment]
Hi, i set firmware Aquila-SpriteT13_N32_UBL-ProUI-PWRLOSS and i cant found powerlost function, weare it place? and i think, if you do firmware for sprit extruder, you can set e steps 424,9 for standart setting

**Comment by classicrocker883** [comment]
> Hi, i set firmware Aquila-SpriteT13_N32_UBL-ProUI-PWRLOSS and i cant found powerlost function, weare it place? and i think, if you do firmware for sprit extruder, you can set e steps 424,9 for standart setting

the power loss function is in the advanced settings from the Control menu. or you can enable it from Tune Menu when printing.

I will automatically have that setting enabled next build update, that was something I overlooked. and I hope you don't mind, but I will set E steps to 425.0 because it is a round number and I want to make it available for all users, just remember to change it for yourself.

**Comment by classicrocker883** [comment]
hi i uploaded a new release.
https://github.com/classicrocker883/MRiscoCProUI/releases/tag/2.1.3f-2

I made changes for you, I hope that helps, if anything needs adjusting let me know
